CC = gcc
CFLAGS = -Wall -g  # Replace -g with -O when not debugging

DEPS    = jlplayerHMW3.c Makefile
OBJS    = jlplayerHMW3.o
EXECS   = jlplayerHMW3

all: $(EXECS)

%.o: %.c $(DEPS)
	$(CC) $(CFLAGS) -c -o $@ $<

$(EXECS): $(OBJS)
	$(CC) $(CFLAGS) -o $@ $^

run: $(EXECS)
	./$(EXECS) $(DIR)

clean:
	/bin/rm -i *.o $(EXECS)