CC=gcc
CFLAGS = -Wall -g 

DEPS    = Makefile
OBJS    = jlplayerHMW3.o
EXECS   = jlplayerHMW3
DIR     = projects

all: $(EXECS)

%.o: %.c $(DEPS)
	$(CC) $(CFLAGS) -c -o $@ $<

$(EXECS): $(OBJS)
	$(CC) $(CFLAGS) -o $@ $^

run: $(EXECS)
	./$(EXECS) $(DIR)

clean:
	/bin/rm -i *.o $(EXECS)